### ISSUE TITLE
[Bug]: OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by shiyishi01** [CHNZYX/Auto_Simulated_Universe#152]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

5.20

### 重现步骤

Fresh download of Auto_Simulated_Universe-main.
-Open Star Rail
-Went to Simulated Universe Room (but this error happened anywhere on the map I tested)
-Run "align.bat"

### 期望的结果是什么？

Recalibrate the align angle

### 实际的结果是什么？

![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/142626697/0253351e-c056-498e-adb0-ae40e059db7a)

C:\STARRAIL\Auto_Simulated_Universe-main>python align_angle.py
INFO [2023-08-18 12:34:28,179] [align_angle.py:32] 开始校准
WARNING [2023-08-18 12:34:28,421] [utils.py:87] 等待游戏窗口
[0]
C:\STARRAIL\Auto_Simulated_Universe-main\align_angle.py:60: RuntimeWarning: divide by zero encountered in scalar divide
  su.multi *= ax / ay
Traceback (most recent call last):
  File "C:\STARRAIL\Auto_Simulated_Universe-main\align_angle.py", line 83, in <module>
    main()
  File "C:\STARRAIL\Auto_Simulated_Universe-main\align_angle.py", line 44, in main
    su.mouse_move(60)
  File "C:\STARRAIL\Auto_Simulated_Universe-main\utils\utils.py", line 1010, in mouse_move
    dx = int(9800 * y * 1295 / self.real_width / 180 * self.multi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot convert float infinity to integer

### 日志记录

No logs because it was just the alignment program

**Comment by shiyishi01** [comment]
It only works on my primary monitor
