### ISSUE TITLE
[Bug]: [9104] Failed to execute script 'gui' due to unhandled exception!

### ISSUE THREAD

**Issue by alex498** [CHNZYX/Auto_Simulated_Universe#195]
### Please make sure you have read the notes above and check the confirmation box below.

- [X] I've tested this using an environment that is clean and free of other non-essential plugins and the problem persists.
- [X] I have looked in [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) for the issue I want to raise and did not find an ISSUE for the same issue.
- [X] I am aware and agree that if this Issue is about something other than the program itself, my Issue may be automatically closed or/and locked unconditionally.
- [X] I am aware and agree that if I do not follow the instructions provided in the template, my Issue may be deleted unconditionally.

### Auto Simulated Universe version （or Commit Id）

08113a0

### Steps to Reproduce

Download "Debug Build" from "GitHub Actions"
Unzip it
Run gui.exe with Admin Rights

### What is the desired outcome?

Start GUI

### What are the actual results?

Program stops after the start cause ppocr lib not builded properly with exe file

### logs

2 0 2 3 - 0 9 - 1 4   1 7 : 0 4 : 5 5 . 3 4 3 6 1 0 2   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 8 2 7   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d .
 Traceback (most recent call last):
  File "gui.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "gui\choose.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "gui\common.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "states.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\utils.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\ocr.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\predict_system.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\rec\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\rec\predict_rec.py", line 26, in <module>
  File "ppocronnx\utility.py", line 289, in get_character_dict
  File "pkgutil.py", line 637, in get_data
  File "PyInstaller\loader\pyimod02_importers.py", line 205, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI127882\\ppocronnx\\model\\ppocr_keys_v1.txt'
[9104] Failed to execute script 'gui' due to unhandled exception!

**Comment by CHNZYX** [comment]
try the latest release

**Comment by alex498** [comment]
```
2 0 2 3 - 0 9 - 1 4   1 9 : 4 0 : 0 1 . 4 2 7 4 0 1 8   [ W : o n n x r u n t i m e : D e f a u l t ,   o n n x r u n t i m e _ p y b i n d _ s t a t e . c c : 1 8 2 7   o n n x r u n t i m e : : p y t h o n : : C r e a t e I n f e r e n c e P y b i n d S t a t e M o d u l e ]   I n i t   p r o v i d e r   b r i d g e   f a i l e d .
 Traceback (most recent call last):
  File "gui.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "gui\choose.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "gui\common.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "states.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\utils.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\ocr.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\predict_system.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\rec\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ppocronnx\rec\predict_rec.py", line 26, in <module>
  File "ppocronnx\utility.py", line 289, in get_character_dict
  File "pkgutil.py", line 637, in get_data
  File "PyInstaller\loader\pyimod02_importers.py", line 205, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\AppData\\Local\\Temp\\_MEI133922\\ppocronnx\\model\\ppocr_keys_v1.txt'
[9136] Failed to execute script 'gui' due to unhandled exception!
```

with Build from 86f2785

**Comment by CHNZYX** [comment]
I don't know why it doesn't work. Maybe you could try a different startup.

**Comment by CHNZYX** [comment]
Release updated, you can try again.

**Comment by alex498** [comment]
Tried last one debug build from https://github.com/CHNZYX/Auto_Simulated_Universe/commit/8cfc944045f828a68300001df0dd67ff396b0799
1) Build with gui.exe -> Same error nothing changed
Also I've noticed that this build doesn't have ocr folder but placing it in the same folder with gui.exe didn't solved the problem
2) Build with notif.exe - >
```
Traceback (most recent call last):
  File "notif.py", line 7, in <module>
ModuleNotFoundError: No module named 'pygame'
```

Also I have tried Release version from (https://github.com/CHNZYX/Auto_Simulated_Universe/releases) https://github.com/CHNZYX/Auto_Simulated_Universe/commit/86f2785e067534ae8cb782bcf44eaf7ade63f279, working instead of auto Debug builds

**Comment by CHNZYX** [comment]
Debug build is deprecated. I will cancel it later.
