### ISSUE TITLE
在这个地图下反复出现list index out of range错误

### ISSUE THREAD

**Issue by hanuxxx** [CHNZYX/Auto_Simulated_Universe#23]
结束程序重新运行，一识别到地图就报错。
手动打完后进入下一区域就正常了

```
INFO [2023-05-25 13:22:56,075] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
WARNING [2023-05-25 13:22:57,649] [utils.py:31] 等待游戏窗口
INFO [2023-05-25 13:23:00,954] [states.py:32] 加载地图
INFO [2023-05-25 13:23:01,333] [states.py:38] 加载地图完成，共 114 张
INFO [2023-05-25 13:23:03,831] [utils.py:584] 地图编号：92676  相似度：0.542528735632184
地图文件：
[ WARN:0@7.905] global loadsave.cpp:244 cv::findDecoder imread_(''): can't open/read file: check file path/integrity
E: 运行函数时出现错误
Traceback (most recent call last):
  File "E:\Downloads\Compressed\CentOS-LLVM-Fork-main\gui.py", line 38, in run
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Downloads\Compressed\CentOS-LLVM-Fork-main\states.py", line 329, in start
    self.route()
  File "E:\Downloads\Compressed\CentOS-LLVM-Fork-main\states.py", line 75, in route
    res = self.normal()
          ^^^^^^^^^^^^^
  File "E:\Downloads\Compressed\CentOS-LLVM-Fork-main\states.py", line 172, in normal
    self.now_loc = (4096 - int(xy[0]), 4096 - int(xy[1]))
                               ~~^^^
IndexError: list index out of range

```
![image](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/23613751/04555fa5-3da7-4f98-b366-d01bf0c02049)

**Comment by CHNZYX** [comment]
运行程序时，请确保处于刚进图的状态。你可以暂离之后再运行试试
