### ISSUE TITLE
7.11 启动弹出错误

### ISSUE THREAD

**Issue by xibaibai9527** [CHNZYX/Auto_Simulated_Universe#303]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经使用一个干净且无其它非必要的插件的环境测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/CHNZYX/Auto_Simulated_Universe/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，如果我不按照模板提供的指示进行填写，则我的 Issue 可能会被无条件删除。

### Auto Simulated Universe 版本 （或 Commit Id）

7.11

### 重现步骤

启动即弹出错误窗口，旧版本能运行

### 期望的结果是什么？

-

### 实际的结果是什么？

-

### 日志记录

Traceback (most recent call last):
  File "gui.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\gui\choose.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\gui\common.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "simul.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\simul\utils.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\simul\ocr.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\onnxocr\onnx_paddleocr.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\onnxocr\predict_system.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\onnxocr\predict_det.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "utils\onnxocr\predict_base.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "onnxruntime\__init__.py", line 57, in <module>
  File "onnxruntime\__init__.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "onnxruntime\capi\_pybind_state.py", line 32, in <module>
ImportError: DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的模块。

### 补充说明（可选）

![2024-07-02_00001](https://github.com/CHNZYX/Auto_Simulated_Universe/assets/19858971/b6caa4de-6316-4c4c-9243-59bf082868de)

**Comment by CHNZYX** [comment]
这是7.0之后使用onnxruntime-directml库一直存在的问题，目前只能尝试下载release中的cpu版本来解决。如果有人知道更好的解决方案可以提出

**Comment by QAQorzseason** [comment]
> 这是7.0之后使用onnxruntime-directml库一直存在的问题，目前只能尝试下载release中的cpu版本来解决。如果有人知道更好的解决方案可以提出

下载替换了cpu版本后无法通过三月七小助手进行集成模式启动了，一启动就会更新新程序然后报这个错误，只能源码启动，并且不能快速启动，只能原版启动，一旦快速启动，就会报这个错误，但原版启动则不会，有什么解决方案能够让快速启动也没问题吗
@CHNZYX

![2%R1UEJ5P%5H{OB7F{3 _34](https://github.com/user-attachments/assets/9fdd849d-46a7-472d-818e-71e9d0592f85)

**Comment by QAQorzseason** [comment]
> > 这是7.0之后使用onnxruntime-directml库一直存在的问题，目前只能尝试下载release中的cpu版本来解决。如果有人知道更好的解决方案可以提出
> 
> 下载替换了cpu版本后无法通过三月七小助手进行集成模式启动了，一启动就会更新新程序然后报这个错误，只能源码启动，并且不能快速启动，只能原版启动，一旦快速启动，就会报这个错误，但原版启动则不会，有什么解决方案能够让快速启动也没问题吗 @CHNZYX
> 
> ![2%R1UEJ5P%5H{OB7F{3 _34](https://private-user-images.githubusercontent.com/176794320/365357128-9fdd849d-46a7-472d-818e-71e9d0592f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDM0MzgsIm5iZiI6MTcyNTcwMzEzOCwicGF0aCI6Ii8xNzY3OTQzMjAvMzY1MzU3MTI4LTlmZGQ4NDlkLTQ2YTctNDcyZC04MThlLTcxZTlkMDU5MmY4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwOTU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTMyNmQ3ZDRiM2RjOTg3MDA0MzFkNmIwYThmN2ZmYTA4MGRiMjY2ODhjZWQxOWJhN2M5YzY5ZGY3MWJkMDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQ0YTJX-mY2Ww1_31Htp1cckKhcm3FP58MUgdWDzOtg)

问题已解决，寻找到项目使用的py文件夹，输入pip install onnxruntime==1.18  后可进行快速启动，不再发出报错

**Comment by qooloo1** [comment]
> > > 这是7.0之后使用onnxruntime-directml库一直存在的问题，目前只能尝试下载release中的cpu版本来解决。如果有人知道更好的解决方案可以提出
> > 
> > 
> > 下载替换了cpu版本后无法通过三月七小助手进行集成模式启动了，一启动就会更新新程序然后报这个错误，只能源码启动，并且不能快速启动，只能原版启动，一旦快速启动，就会报这个错误，但原版启动则不会，有什么解决方案能够让快速启动也没问题吗 [@CHNZYX](https://github.com/CHNZYX)
> > ![2%R1UEJ5P%5H{OB7F{3 _34](https://private-user-images.githubusercontent.com/176794320/365357128-9fdd849d-46a7-472d-818e-71e9d0592f85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MDM0MzgsIm5iZiI6MTcyNTcwMzEzOCwicGF0aCI6Ii8xNzY3OTQzMjAvMzY1MzU3MTI4LTlmZGQ4NDlkLTQ2YTctNDcyZC04MThlLTcxZTlkMDU5MmY4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwOTU4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTMyNmQ3ZDRiM2RjOTg3MDA0MzFkNmIwYThmN2ZmYTA4MGRiMjY2ODhjZWQxOWJhN2M5YzY5ZGY3MWJkMDVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JQ0YTJX-mY2Ww1_31Htp1cckKhcm3FP58MUgdWDzOtg)
> 
> 问题已解决，寻找到项目使用的py文件夹，输入pip install onnxruntime==1.18 后可进行快速启动，不再发出报错

请问你是在哪个py资料夹?
