### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by michael-pptf** [CHNZYX/Auto_Simulated_Universe#47]
INFO [2023-06-08 10:00:18,557] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
WARNING [2023-06-08 10:00:25,003] [utils.py:76] 等待游戏窗口
E: 运行函数时出现错误
Traceback (most recent call last):
  File "C:\Users\michael\Downloads\Auto_Simulated_Universe-main\Auto_Simulated_Universe-main\gui\choose.py", line 31, in run
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\michael\Downloads\Auto_Simulated_Universe-main\Auto_Simulated_Universe-main\states.py", line 57, in __init__
    notif('开始运行',f'初始计数：{self.count}')
  File "C:\Users\michael\Downloads\Auto_Simulated_Universe-main\Auto_Simulated_Universe-main\utils\utils.py", line 30, in notif
    cnt=s[0].strip('\n')
        ~^^^
IndexError: list index out of range
Exception in thread Thread-13 (start):
Traceback (most recent call last):
  File "C:\Users\michael\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\michael\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\michael\Downloads\Auto_Simulated_Universe-main\Auto_Simulated_Universe-main\gui\choose.py", line 65, in start
    run(page.su.start)
        ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start'

**Comment by michael-pptf** [comment]
After a failed launch, I needed to delete all files under /logs folder. I was able to track down the issue to the encoding the log writer was using, which isn't specified.

In utils/utils.py, line 42:
`with open('logs/notif.txt','w', encoding="utf-8") as fh:`
using `encoding="utf-8"` resolves the issue

**Comment by CHNZYX** [comment]
fixed, thanks

**Comment by michael-pptf** [comment]
> fixed, thanks

I found a few more places that needs to have this bit enabled. Namely writing and reading the logs. I think there are four lines in your script that is relavant to log file reading and writing, and I have to add `encoding='utf-8'` to all of them.
