### ISSUE TITLE
[报错]脚本运行一段时间后会出现报错

### ISSUE THREAD

**Issue by UMP45-Team404** [CHNZYX/Auto_Simulated_Universe#50]
一晚上出现了两次，看日志像是识别不到地图？人工点一下运行恢复正常，检查了一下地图不需要更新。日志和报错时游戏位置如下：
[![pCEDhfs.png](https://s1.ax1x.com/2023/06/10/pCEDhfs.png)](https://imgse.com/i/pCEDhfs)
[![pCEDo60.png](https://s1.ax1x.com/2023/06/10/pCEDo60.png)](https://imgse.com/i/pCEDo60)

**Comment by Ding-Kyoma** [comment]
处于跟楼主相同的地图位置，相同的报错信息，同样出现多次，位置在世界6的一张地图里，地图编号19787：

```
INFO [2023-06-09 05:50:14,687] [utils.py:226] 匹配到图片 ./imgs/choose_bless.jpg 相似度 0.972192 阈值 0.970000
INFO [2023-06-09 05:50:15,397] [utils.py:226] 匹配到图片 ./imgs/bless/4.jpg 相似度 0.981959 阈值 0.970000
INFO [2023-06-09 05:50:19,126] [states.py:478] 匹配不到任何图标
INFO [2023-06-09 05:50:23,366] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.991960 阈值 0.955000
INFO [2023-06-09 05:50:24,448] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.991614 阈值 0.955000
INFO [2023-06-09 05:50:24,522] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.991612 阈值 0.970000
INFO [2023-06-09 05:50:25,241] [utils.py:226] 匹配到图片 ./imgs/f.jpg 相似度 0.991614 阈值 0.970000
INFO [2023-06-09 05:50:25,244] [utils.py:226] 匹配到图片 ./imgs/tele.jpg 相似度 0.998797 阈值 0.965000
INFO [2023-06-09 05:50:25,245] [states.py:254] 地图-1已完成,相似度-1,进入6层
INFO [2023-06-09 05:50:28,928] [states.py:314] 地图编号：-1  相似度：-1
Traceback (most recent call last):
  File "C:\Users\13268\Downloads\Auto_Simulated_Universe-main\states.py", line 665, in main
    su.start()
  File "C:\Users\13268\Downloads\Auto_Simulated_Universe-main\states.py", line 654, in start
    self.route()
  File "C:\Users\13268\Downloads\Auto_Simulated_Universe-main\states.py", line 116, in route
    res = self.normal()
          ^^^^^^^^^^^^^
  File "C:\Users\13268\Downloads\Auto_Simulated_Universe-main\states.py", line 318, in normal
    self.now_pth = "imgs/maps/" + self.now_map + "/"
                   ~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: can only concatenate str (not "int") to str
INFO [2023-06-09 05:50:28,933] [states.py:606] 尝试停止运行
```

**Comment by CHNZYX** [comment]
已更新
