### ISSUE TITLE
随机TypeError

### ISSUE THREAD

**Issue by maikirakiwi** [CHNZYX/Auto_Simulated_Universe#6]
```py
Traceback (most recent call last):
  File "C:\Users\maiki\DOCUME~1\HONKAI~1\AUTO_S~1\states.py", line 253, in <module>
    main()
  File "C:\Users\maiki\DOCUME~1\HONKAI~1\AUTO_S~1\states.py", line 249, in main
    su.route()
  File "C:\Users\maiki\DOCUME~1\HONKAI~1\AUTO_S~1\states.py", line 57, in route
    res=self.normal()
        ^^^^^^^^^^^^^
  File "C:\Users\maiki\DOCUME~1\HONKAI~1\AUTO_S~1\states.py", line 155, in normal
    self.get_direc()
  File "C:\Users\maiki\DOCUME~1\HONKAI~1\AUTO_S~1\utils\utils.py", line 278, in get_direc
    ang=math.atan2(loc[0]-self.real_loc[0],loc[1]-self.real_loc[1])/math.pi*180
                   ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'tuple' and 'int'```

**Comment by htshts1115** [comment]
我也遇到一样的问题
./imgs/f.jpg 0.9994151592254639 0.98
./imgs/f.jpg 0.9994171857833862 0.98
./imgs/tele.jpg 0.9954557418823242 0.98
相似度： 0.36246786632390743 地图编号： 47312
{((13.26923076923077, 77.84615384615384), 3), ((20.133333333333333, 62.233333333333334), 1)}
./imgs/f.jpg 0.9990455508232117 0.98
./imgs/f.jpg 0.9993380308151245 0.98
done!
./imgs/f.jpg 0.9993322491645813 0.98
./imgs/event.jpg 0.9940212368965149 0.98
./imgs/event.jpg 0.9929016828536987 0.98
./imgs/event.jpg 0.9932687282562256 0.98
./imgs/arrow.jpg 0.9985910058021545 0.98
./imgs/star.jpg 0.9882098436355591 0.965
./imgs/f.jpg 0.9993345141410828 0.98
./imgs/f.jpg 0.9993345141410828 0.98
done!
./imgs/f.jpg 0.9978992342948914 0.98
Traceback (most recent call last):
  File "C:\Users\Tianshen\DOWNLO~1\AUTO_S~1\states.py", line 253, in <module>
    main()
  File "C:\Users\Tianshen\DOWNLO~1\AUTO_S~1\states.py", line 249, in main
    su.route()
  File "C:\Users\Tianshen\DOWNLO~1\AUTO_S~1\states.py", line 57, in route
    res=self.normal()
        ^^^^^^^^^^^^^
  File "C:\Users\Tianshen\DOWNLO~1\AUTO_S~1\states.py", line 155, in normal
    self.get_direc()
  File "C:\Users\Tianshen\DOWNLO~1\AUTO_S~1\utils\utils.py", line 278, in get_direc
    ang=math.atan2(loc[0]-self.real_loc[0],loc[1]-self.real_loc[1])/math.pi*180
                   ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

**Comment by CHNZYX** [comment]
已解决
