### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by forchannot** [CHNZYX/Auto_Simulated_Universe#60]
已经确认通过update.bat更新到了最新版本
无论是`python states.py --find=1`启动还是`python gui.py`启动都会报错，已经使用了管理员权限，报错信息如下
```python
❯ python states.py --find=1
INFO [2023-06-12 11:19:25,640] [states.py:706] find: 1, debug: 0, show_map: 0
WARNING [2023-06-12 11:19:25,645] [utils.py:77] 等待游戏窗口
Traceback (most recent call last):
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 724, in <module>
    main()
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 707, in main
    su = SimulatedUniverse(find, debug, show_map, speed, update)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 56, in __init__
    self.update_count()
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 542, in update_count
    s=fh.readlines()
      ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 3: invalid continuation byte
```
```python
❯ python gui.py
INFO [2023-06-12 11:19:38,084] [admin.py:29] isUserAdmin - CheckTokenMembership returned: True
WARNING [2023-06-12 11:19:51,229] [utils.py:77] 等待游戏窗口
E: 运行函数时出现错误
Traceback (most recent call last):
  File "D:\Download\github\Auto_Simulated_Universe-main\gui\choose.py", line 31, in run
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 56, in __init__
    self.update_count()
  File "D:\Download\github\Auto_Simulated_Universe-main\states.py", line 542, in update_count
    s=fh.readlines()
      ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 3: invalid continuation byte
Exception in thread Thread-28 (start):
Traceback (most recent call last):
  File "E:\miniconda\envs\autosr\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "E:\miniconda\envs\autosr\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Download\github\Auto_Simulated_Universe-main\gui\choose.py", line 73, in start
    run(page.su.start)
        ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start'
```

**Comment by forchannot** [comment]
使用release包没问题了，clone的不行，奇怪

**Comment by CHNZYX** [comment]
编码问题
