### ISSUE TITLE
校準時出現錯誤

### ISSUE THREAD

**Issue by seriaati** [CHNZYX/Auto_Simulated_Universe#76]
```ps
(.venv) PS C:\Users\seria\source\repos\Auto_Simulated_Universe-4.84> python .\align_angle.py
INFO [2023-06-17 19:55:06,168] [align_angle.py:30] 开始校准
WARNING [2023-06-17 19:55:06,183] [utils.py:77] 等待游戏窗口
[0]
C:\Users\seria\source\repos\Auto_Simulated_Universe-4.84\align_angle.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  su.multi *= ax / ay
Traceback (most recent call last):
  File "C:\Users\seria\source\repos\Auto_Simulated_Universe-4.84\align_angle.py", line 81, in <module>
    main()
  File "C:\Users\seria\source\repos\Auto_Simulated_Universe-4.84\align_angle.py", line 42, in main
    su.mouse_move(60)
  File "C:\Users\seria\source\repos\Auto_Simulated_Universe-4.84\utils\utils.py", line 903, in mouse_move
    dx = int(9800 * y * 1295 / self.real_width / 180 * self.multi)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: cannot convert float infinity to integer
```

**Comment by CHNZYX** [comment]
确保鼠标在游戏界面，确保打开管理员模式

**Comment by seriaati** [comment]
用管理員身分執行後就可以了
