### ISSUE TITLE
单显示器下依然出现了进入事件和黑塔界面时闪退的问题

### ISSUE THREAD

**Issue by bf109f4** [CHNZYX/Auto_Simulated_Universe#90]
首先感谢大佬
错误日志如下：

INFO [2023-06-22 19:51:40,367] [states.py:229] 地图-1已完成,相似度-1,进入10层
INFO [2023-06-22 19:51:40,982] [states.py:460] 匹配不到任何图标
INFO [2023-06-22 19:51:41,656] [states.py:460] 匹配不到任何图标
INFO [2023-06-22 19:51:42,398] [states.py:460] 匹配不到任何图标
INFO [2023-06-22 19:51:43,593] [states.py:460] 匹配不到任何图标
INFO [2023-06-22 19:51:44,931] [utils.py:535] 交互点相似度0.921389639377594，位置135,65
事件（
INFO [2023-06-22 19:51:53,143] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.992449 阈值 0.970000
INFO [2023-06-22 19:51:53,664] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.992226 阈值 0.970000
Traceback (most recent call last):
  File "E:\VideoGames\auto_universe_4.92\states.py", line 657, in main
    su.start()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 646, in start
    self.route()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 110, in route
    res = self.normal()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 377, in normal
    self.get_direc_only_minimap()
  File "E:\VideoGames\auto_universe_4.92\utils\utils.py", line 620, in get_direc_only_minimap
    pyautogui.keyDown("w")
  File "E:\MINIconda\envs\auto_simul_universe\lib\site-packages\pyautogui\__init__.py", line 593, in wrapper
    failSafeCheck()
  File "E:\MINIconda\envs\auto_simul_universe\lib\site-packages\pyautogui\__init__.py", line 1734, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
INFO [2023-06-22 19:52:04,005] [states.py:588] 尝试停止运行

INFO [2023-06-22 20:26:44,723] [states.py:229] 地图-1已完成,相似度-1,进入12层
INFO [2023-06-22 20:26:46,006] [utils.py:546] 黑塔相似度0.9843676686286926，位置164,101
INFO [2023-06-22 20:26:51,726] [utils.py:546] 黑塔相似度0.9199695587158203，位置149,108
黑塔
INFO [2023-06-22 20:27:01,210] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991544 阈值 0.970000
INFO [2023-06-22 20:27:01,749] [utils.py:234] 匹配到图片 ./imgs/f.jpg 相似度 0.991484 阈值 0.970000
Traceback (most recent call last):
  File "E:\VideoGames\auto_universe_4.92\states.py", line 657, in main
    su.start()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 646, in start
    self.route()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 110, in route
    res = self.normal()
  File "E:\VideoGames\auto_universe_4.92\states.py", line 377, in normal
    self.get_direc_only_minimap()
  File "E:\VideoGames\auto_universe_4.92\utils\utils.py", line 620, in get_direc_only_minimap
    pyautogui.keyDown("w")
  File "E:\MINIconda\envs\auto_simul_universe\lib\site-packages\pyautogui\__init__.py", line 593, in wrapper
    failSafeCheck()
  File "E:\MINIconda\envs\auto_simul_universe\lib\site-packages\pyautogui\__init__.py", line 1734, in failSafeCheck
    raise FailSafeException(
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
INFO [2023-06-22 20:27:11,386] [states.py:588] 尝试停止运行

单屏还是报错了，4.92和4.963都出现了这个问题

**Comment by CHNZYX** [comment]
抱歉，我修复不了无法在自己电脑上复现的bug。看上去鼠标移到了屏幕之外，这是库函数的报错，需要你自己解决。

**Comment by bf109f4** [comment]
顺便问下大佬用的是python3.11吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月22日(周四) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CHNZYX/Auto_Simulated_Universe] 单显示器下依然出现了进入事件和黑塔界面时闪退的问题 (Issue #90)




 
抱歉，我修复不了无法在自己电脑上复现的bug。看上去鼠标移到了屏幕之外，这是库函数的报错，需要你自己解决。

**Comment by CHNZYX** [comment]
不是，是3.9

**Comment by CHNZYX** [comment]
屏蔽了这个错误，如果出现异常可以继续开issue
